(()=>{'use strict';
const reviews=window.MM_REVIEWS||[], albums=window.MM_ALBUMS||[];
const reactions=[['horns','🤘','Legendär'],['fire','🔥','Banger'],['skull','☠️','Brutal'],['dark','🌑','Atmosphäre'],['heart','🖤','Gänsehaut']];
function load(){document.documentElement.classList.add('ready')} setTimeout(load,1000); window.addEventListener('load',()=>setTimeout(load,200));
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const art=x=>`<div class="artwork"><span>${esc(x.genre)}</span><div class="mark">${esc(x.symbol)}</div><b>${esc(x.poster)}</b><small>${esc(x.artist)}</small></div>`;
const store=n=>{try{return JSON.parse(localStorage.getItem(n)||'{}')}catch(e){return {}}};
const save=(n,d)=>{try{localStorage.setItem(n,JSON.stringify(d))}catch(e){}};
const seed=(id,k)=>8+[...id+k].reduce((a,c)=>a+c.charCodeAt(0),0)%30;
const count=(id,k)=>seed(id,k)+Number(store('mm_reactions')?.[id]?.[k]||0);
const scores=s=>Object.entries(s||{}).map(([n,v])=>`<div class="score-row"><span>${esc(n)}</span><div class="bar"><i style="width:${Number(v)*10}%"></i></div><b>${esc(v)}/10</b></div>`).join('');
function reactionHtml(id){const u=store('mm_user_reactions')[id]||'';return `<div class="block"><span>Reagieren</span><p>Welche Stimmung trifft es?</p><div class="reactions">${reactions.map(([k,e,l])=>`<button class="${u===k?'active':''}" data-react="${k}" data-id="${id}">${e} ${l} <b>${count(id,k)}</b></button>`).join('')}</div></div>`}
function wireReact(){ $$('[data-react]').forEach(b=>b.onclick=()=>{let d=store('mm_reactions'),u=store('mm_user_reactions'),id=b.dataset.id,k=b.dataset.react;if(u[id]!==k){u[id]=k;d[id]=d[id]||{};d[id][k]=Number(d[id][k]||0)+1;save('mm_reactions',d);save('mm_user_reactions',u)}; openItem(id); updateCommunity();});}
function openSong(id){const r=reviews.find(x=>x.id===id); if(!r)return; $('main').classList.add('hidden'); const d=$('#detail'); d.innerHTML=`<span class="back" onclick="showHome()">← Zurück</span><section class="detail-layout">${art(r)}<article class="detail-main"><span>Song Review #${esc(r.num)}</span><h1>${esc(r.title)}</h1><h2>${esc(r.artist)} · ${esc(r.genre)} · ${esc(r.year)}</h2><div class="block"><span>05Alex sagt</span><p>${esc(r.text)}</p></div><div class="block"><span>MetalScore</span><h2>${esc(r.score)}/10</h2>${scores(r.scores)}</div><div class="block"><span>Lieblingsmoment</span><p>${esc(r.moment)}</p></div><div class="block"><span>Wann höre ich den Song?</span><p>${esc(r.listen)}</p></div>${reactionHtml(r.id)}</article></section>`; d.classList.remove('hidden'); wireReact(); scrollTo(0,0);}
function openAlbum(id){const a=albums.find(x=>x.id===id); if(!a)return; $('main').classList.add('hidden'); const d=$('#detail'); d.innerHTML=`<span class="back" onclick="showHome()">← Zurück</span><section class="detail-layout">${art(a)}<article class="detail-main"><span>Album Review #${esc(a.num)}</span><h1>${esc(a.title)}</h1><h2>${esc(a.artist)} · ${esc(a.genre)} · ${esc(a.year)}</h2><div class="block"><span>Bewertung</span><h2>${esc(a.score)}/10</h2></div><div class="block"><span>05Alex sagt</span><p>${esc(a.text)}</p></div><div class="block"><span>Kritik</span><p>${esc(a.criticism)}</p></div><div class="block"><span>Top 3 Songs</span><ol>${a.highlights.map(x=>`<li>${esc(x[0])}${x[1]?' — '+esc(x[1]):''}</li>`).join('')}</ol></div><div class="block"><span>Atmosphäre</span><p>${a.mood.map(esc).join(' · ')}</p></div><div class="block"><span>AlbumScore</span>${scores(a.scores)}</div><div class="block"><span>Lieblingsmoment</span><p>${esc(a.moment)}</p></div>${reactionHtml(a.id)}</article></section>`; d.classList.remove('hidden'); wireReact(); scrollTo(0,0);}
function openItem(id){albums.find(x=>x.id===id)?openAlbum(id):openSong(id)}
window.showHome=()=>{$('#detail').classList.add('hidden');$('main').classList.remove('hidden');scrollTo(0,0)}
function total(x){return reactions.reduce((a,[k])=>a+count(x.id,k),0)}
function updateCommunity(){const items=[...reviews,...albums].sort((a,b)=>total(b)-total(a)); const w=items[0], top=reactions.map(([k,e,l])=>[k,e,l,count(w.id,k)]).sort((a,b)=>b[3]-a[3])[0]; $('#community').innerHTML=`<div><span>Community feiert gerade</span><h2>${esc(w.title)}</h2><p>${esc(w.artist)} · ${esc(w.genre)} · ${total(w)} Reaktionen</p></div><strong>${top[1]}</strong>`; $('#community').onclick=()=>openItem(w.id);}
function init(){ $$('[data-open]').forEach(x=>x.onclick=()=>openItem(x.dataset.open)); $$('.card,.album-card').forEach(x=>x.onclick=()=>openItem(x.dataset.id)); $('#randomBtn').onclick=()=>{const all=[...reviews,...albums], x=all[Math.floor(Math.random()*all.length)]; openItem(x.id)}; $('#search').oninput=e=>{const q=e.target.value.toLowerCase(); $$('[data-search]').forEach(x=>x.style.display=x.dataset.search.includes(q)?'':'none')}; updateCommunity();}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();